# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Ratul
tagline:             'DevOps Engineer'
description:         'DevOps is not a goal, but a never-ending process of continual improvement. If you automate a mess, you get an automated mess. The most powerful tool we have as developers is automation. My linkedin <a href="https://www.linkedin.com/in/ratul-basak" target="_blank">Ratul</a>'
url:                 http://syslearn.cf
baseurl:             'ratulbasak.github.io'
paginate:            5
github:              https://github.com/ratulbasak


# About/contact
author:
  name:              Ratul Basak
  url:               https://twitter.com/mdo
  email:             ratulbasak93@gmail.com

# Custom vars
version:             1.0.0
